development:
  host: localhost
  database: badgify_development

test:
  host: localhost
  database: badgify_test

staging:
  uri: <%= ENV['MONGOLAB_URI'] %>

production:
  uri: <%= ENV['MONGOLAB_URI'] %>
